[package]
name = "xyz2png"
edition = "2018"
version = "1.1.0"
build = "build.rs"
authors = ["Napen123 <napen123@gmail.com>"]

[dependencies]
byteorder = "1"
miniz_oxide = "0.2"

[build-dependencies]
cc = "1.0"
